# Generated by Django 5.0.6 on 2024-06-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('url', models.CharField(max_length=1024)),
                ('hd_url', models.CharField(max_length=1024)),
                ('copyright', models.CharField(max_length=1024)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='nasa_image_date_946700_idx')],
            },
        ),
    ]
