# Generated by Django 5.0.6 on 2024-07-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('url', models.CharField(max_length=1024)),
                ('media_type', models.CharField(max_length=32)),
                ('extra_info', models.CharField(max_length=1024)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['date'], name='nasa_media_date_cb9813_idx'),
        ),
    ]
